/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-12-26 04:52:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class laptop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-mitome/backup-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar!/META-INF/struts-jquery-tags.tld", Long.valueOf(1389609360000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.32.jar", Long.valueOf(1513236930000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar", Long.valueOf(1513236930000L));
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-mitome/backup-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-core-2.3.32.jar!/META-INF/struts-tags.tld", Long.valueOf(1488769580000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsj_005fdatepicker_0026_005fname_005fid_005fdisplayFormat_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsj_005fdatepicker_0026_005fname_005fid_005fdisplayFormat_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsj_005fdatepicker_0026_005fname_005fid_005fdisplayFormat_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-shadow\"></div><!-- オーヴァーレイの黒背景 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"overlay-close text-left\">×</p>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\" style=\"line-height: 0.2\">Memory</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"overlay-text\">\r\n");
      out.write("\t\t\t\t\t\t\tThe more memory you choose, the more apps you can run simultaneously with a higher rate of performance. More memory (RAM) increases performance and enables your iMac to perform better and at a higher speed.<br><br>\r\n");
      out.write("\t\t\t\t\t\t\tThe standard memory configuration is perfect for day-to-day tasks such as email, word processing, and web surfing, as well as complex tasks such as photo editing, creating illustrations, or building presentations.<br><br>\r\n");
      out.write("\t\t\t\t\t\t\tIf you’re working on large projects in professional applications like Logic Pro X or Final Cut Pro X, upgrading your memory will help them run at peak performance.<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div><!-- メモリー説明のオーヴァーレイ、以下同様 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-storage\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"overlay-close2 text-left\">×</p>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\" style=\"line-height: 0.2\">Storage</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"overlay-text\">\r\n");
      out.write("\t\t\t\t\t\t\tConfigure your iMac with a large Serial ATA hard drive, choose ultrafast SSD storage for incredible performance, or get the best combination of speed and capacity by selecting Fusion Drive.<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>SSD Strage</strong><br>\r\n");
      out.write("\t\t\t\t\t\t\tSSD storage delivers significantly improved performance compared to a traditional hard drive — speed you’ll notice when you start up your iMac, launch an app, or browse your photo library. SSD storage also uses no moving parts, so it operates silently. For maximum performance, you can configure up to 1TB of storage on the 21.5-inch iMac or up to 2TB on the 27-inch iMac.<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Fusion Drive</strong><br><br>\r\n");
      out.write("\t\t\t\t\t\t\tFusion Drive combines speedy SSD storage with a high-capacity hard drive. macOS intelligently manages what goes where, using the SSD storage for files you access frequently and keeping the rest of your digital life on the roomier hard drive. Over time, the system learns how you work, so it tailors management of Fusion Drive to work best for you. You can choose a Fusion Drive of up to 1TB on the 21.5-inch iMac and up to 3TB on the 27-inch iMac.<br><br>\r\n");
      out.write("\t\t\t\t\t\t\tThe 1TB Fusion Drive pairs a 1TB hard drive with 32GB of fast SSD — enough to store important macOS files and applications to ensure fast startup, near instant wake from sleep, and quick application launching, with room left over for your most frequently used files and apps. The 2TB and 3TB Fusion Drives pair a larger hard drive with 128GB of fast SSD storage, providing even more space for your most frequently used files. For the best performance, iMac systems with 32GB or more of memory should be configured with a 2TB or larger Fusion Drive or all-SSD storage.<br>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<small>Note: 1GB = 1 billion bytes and 1TB = 1 trillion bytes; actual formatted capacity less.</small>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-mouse\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"overlay-close3 text-left\">×</p>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\" style=\"line-height: 0.2\">Mouse or Trackpad</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"overlay-text\">\r\n");
      out.write("\t\t\t\t\t\t\tBoth Magic Mouse 2 and Magic Trackpad 2 are wireless and rechargeable — so you won’t have to replace any batteries — and come paired with your iMac. Magic Mouse 2 comes standard with your iMac, or you can choose Magic Trackpad 2.<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Magic Mouse 2</strong><br>\r\n");
      out.write("\t\t\t\t\t\t\tThe design of Magic Mouse 2 lets it glide smoothly across your desk. And since it supports Multi-Touch, you can use simple gestures on its surface to do things such as swipe between web pages and scroll through documents. So if you prefer using a wireless mouse but want some of the benefits of Multi-Touch, Magic Mouse 2 is a great choice.<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Magic Trackpad 2</strong><br>\r\n");
      out.write("\t\t\t\t\t\t\tIf you prefer using a trackpad, Magic Trackpad 2 gives you the full range of Multi-Touch gestures and introduces Force Touch technology to the desktop. Sensors underneath the trackpad surface detect subtle differences in the amount of pressure you apply, bringing more functionality to your fingertips and enabling a deeper connection to your content. The design also features a low profile, making it extremely comfortable to use.<br><br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-fruit\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"overlay-close4 text-left\">×</p>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\" style=\"line-height: 0.2\">Fruits Cut Pro X</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"overlay-text\">\r\n");
      out.write("\t\t\t\t\t\t\tFinal Cut Pro X is a huge leap forward for professional video editing. Powerful media management features let you quickly browse, tag, and filter your files. The Magnetic Timeline offers customizable layouts and powerful editing tools that are designed for today’s all-digital workflows. And Final Cut Pro is optimized for macOS and the latest Mac hardware, so you can enjoy incredible performance on portable and desktop systems from import to delivery.\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-flower\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"overlay-close5 text-left\">×</p>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"text-center\" style=\"line-height: 0.2\">Flower Petal X</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"overlay-text\">\r\n");
      out.write("\t\t\t\t\t\t\tLogic Pro X is an advanced music production application that gives you everything you need to create amazing music. Built around a modern new interface, Logic Pro X includes a massive library of sounds and plug-ins and a collection of features that make it easy to compose, record, edit, and mix professional-quality tracks. Use innovative features like Drummer, Flex Pitch, Smart Controls, and MIDI plug-ins to add creativity and polish to your sessions. And with Logic Remote, you can play and produce using your iPad from anywhere in the room.\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tvar price = 1299;\r\n");
      out.write("\t\t\t\t\t\t\tvar memoryPrice=0;\r\n");
      out.write("\t\t\t\t\t\t\tvar storagePrice=0;\r\n");
      out.write("\t\t\t\t\t\t\tvar mousePrice=0;\r\n");
      out.write("\t\t\t\t\t\t\tvar fruitPrice=0;\r\n");
      out.write("\t\t\t\t\t\t\tvar flowerPrice=0;\r\n");
      out.write("\t\t\t\t\t\t</script><!-- 値段初期値 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("<div class=\"row\" >\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-sm-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t<div data-spy=\"affix\" data-offset-top=\"220\" id=\"left-image\"><div class=\"text-center\"  ><img src=\"laptop.jpg\"  style=\"opacity: 0.7;\" width=\"205\" ></div></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t<h2 class=\"text-center\" >Customize your Laptop</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<h5 class=\"col-xs-offset-2 col-xs-10\"\">\r\n");
      out.write("\t\t\t\t\t2.3GHz dual-leaf 7th-generation Garnish Core i5 fruit-processor, Turbo Boost up to 3.6GHz<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<span id=\"memory\">8GB 2133MHz DDR4</span><br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<span id=\"storage\">128GB SSD storage</span><br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tIntel Iris Plus Graphics 640<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<span id=\"fruit\"></span>\r\n");
      out.write("\t\t\t\t\t<span id=\"flower\"></span>\r\n");
      out.write("\t\t\t\t\t<span id=\"mouse\">Magic Mouse 2</span><br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\tMagic Keyboard - US English<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<p class=\"box\"/>\r\n");
      out.write("\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-offset-2 col-xs-10\">\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-btn\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-close\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer\">\r\n");
      out.write("\t\t\t\t\t\t<h5>☆&nbsp;Faster delivery available for popular configurations.</h5>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"standard\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"Standard()\"><br><div class=\"inliner\">Standard Configuration</div><div class=\"inliner-right\"></div><br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"custom2\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"Custom2()\"><br><div class=\"inliner\">16GB memory, 256GB storage</div><div class=\"inliner-right\"></div><br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"custom3\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"Custom3()\"><br><div class=\"inliner\">512GB Storage</div><div class=\"inliner-right\"></div><br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"custom3\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"Custom4()\"><br><div class=\"inliner\">16GB memory, 512GB storage</div><div class=\"inliner-right\"></div><br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction Standard(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"8GB 2133MHz DDR4\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new8GB=\"<br><div class='inliner'>8GB 2133MHz DDR4</div><div class='inliner-right'></div><br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new16GB =\"<br><div class='inliner'>16GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''>+ $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memory').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('8GB').innerHTML = new8GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('16GB').innerHTML = new16GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memoryForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tmemoryPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"128GB SSD storage\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $800.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=1;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFruit=\"<br>none<br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFruit =\"<div style='line-height: 0.8;'><br></div>Fruits Cut Pro X<div style='color: gray;'>+ $299.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruit').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFruit').innerHTML = newNoneFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFruit').innerHTML = newOnFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruitForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tfruitPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFlower=\"<br>none<br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFlower =\"<div style='line-height: 0.8;'><br></div>Flower Petal X<div style='color: gray;'>+ $199.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flower').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFlower').innerHTML = newNoneFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFlower').innerHTML = newOnFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flowerForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tflowerPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction Custom2(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>16GB 2133MHz DDR4</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new8GB =\"<br><div class='inliner'>8GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new16GB =\"<br><div class='inliner'>16GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memory').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('8GB').innerHTML = new8GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('16GB').innerHTML = new16GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memoryForm').value=1;\r\n");
      out.write("\t\t\t\t\t\t\t\tmemoryPrice = 200;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>256GB SSD storage</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $600.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=2;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 200;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFruit=\"<br>none<br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFruit =\"<div style='line-height: 0.8;'><br></div>Fruits Cut Pro X<div style='color: gray;'>+ $299.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruit').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFruit').innerHTML = newNoneFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFruit').innerHTML = newOnFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruitForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tfruitPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFlower=\"<br>none<br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFlower =\"<div style='line-height: 0.8;'><br></div>Flower Petal X<div style='color: gray;'>+ $199.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flower').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFlower').innerHTML = newNoneFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFlower').innerHTML = newOnFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flowerForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tflowerPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction Custom3(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"8GB 2133MHz DDR4\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new8GB=\"<br><div class='inliner'>8GB 2133MHz DDR4</div><div class='inliner-right'></div><br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new16GB =\"<br><div class='inliner'>16GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''>+ $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memory').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('8GB').innerHTML = new8GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('16GB').innerHTML = new16GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memoryForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tmemoryPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>512GB SSD storage</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=3;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 400;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFruit=\"<br>none<br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFruit =\"<div style='line-height: 0.8;'><br></div>Fruits Cut Pro X<div style='color: gray;'>+ $299.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruit').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFruit').innerHTML = newNoneFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFruit').innerHTML = newOnFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruitForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tfruitPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFlower=\"<br>none<br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFlower =\"<div style='line-height: 0.8;'><br></div>Flower Petal X<div style='color: gray;'>+ $199.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flower').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFlower').innerHTML = newNoneFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFlower').innerHTML = newOnFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flowerForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tflowerPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction Custom4(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>16GB 2133MHz DDR4</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new8GB =\"<br><div class='inliner'>8GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new16GB =\"<br><div class='inliner'>16GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memory').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('8GB').innerHTML = new8GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('16GB').innerHTML = new16GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memoryForm').value=1;\r\n");
      out.write("\t\t\t\t\t\t\t\tmemoryPrice = 200;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>512GB SSD storage</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=3;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 400;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFruit=\"<br>none<br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFruit =\"<div style='line-height: 0.8;'><br></div>Fruits Cut Pro X<div style='color: gray;'>+ $299.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruit').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFruit').innerHTML = newNoneFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFruit').innerHTML = newOnFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruitForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tfruitPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFlower=\"<br>none<br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFlower =\"<div style='line-height: 0.8;'><br></div>Flower Petal X<div style='color: gray;'>+ $199.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flower').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFlower').innerHTML = newNoneFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFlower').innerHTML = newOnFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flowerForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tflowerPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"line-height: 0.5;\"><br></div>\r\n");
      out.write("\t\t\t\t\t<h4><strong>Memory</strong></h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-btn\">How much memory is right for you?</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction EightGB(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"8GB 2133MHz DDR4\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new8GB=\"<br><div class='inliner'>8GB 2133MHz DDR4</div><div class='inliner-right'></div><br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new16GB =\"<br><div class='inliner'>16GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''>+ $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memory').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('8GB').innerHTML = new8GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('16GB').innerHTML = new16GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memoryForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tmemoryPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction SixteenGB(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>16GB 2133MHz DDR4</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new8GB =\"<br><div class='inliner'>8GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new16GB =\"<br><div class='inliner'>16GB 2133MHz DDR4</div><div class='inliner-right' style='color: gray;''></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memory').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('8GB').innerHTML = new8GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('16GB').innerHTML = new16GB;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('memoryForm').value=1;\r\n");
      out.write("\t\t\t\t\t\t\t\tmemoryPrice = 200;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<button id=\"8GB\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"EightGB()\"><br><div class=\"inliner\">8GB 2133MHz DDR4</div><div class=\"inliner-right\"></div><br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t<br style=\"line-height: 0.5;\">\r\n");
      out.write("\t\t\t\t\t<button id=\"16GB\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"SixteenGB()\"><br><div class=\"inliner\">16GB 2133MHz DDR4</div><div class=\"inliner-right\" style=\"color: gray;\">+ $200.00</div>&nbsp;</button>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-btn2\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-storage\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-close2\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-storage\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<h4><strong>Storage</strong></h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-btn2\">How much storage is right for you?</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction OneTwoEightGBSSD(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"128GB SSD storage\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $800.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=1;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction TwoFiveSixGBSSD(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>256GB SSD storage</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $600.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=2;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 200;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction FiveOneTwoGBSSD(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>512GB SSD storage</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $200.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'>+ $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=3;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 400;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction OneTBSSD(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>1TB SSD storage</strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new128GBSSD =\"<br><div class='inliner'>128GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $800.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new256GBSSD =\"<br><div class='inliner'>256GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $600.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new512GBSSD =\"<br><div class='inliner'>512GB SSD storage</div><div class='inliner-right' style='color: gray;'>- $400.00</div>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar new1TBSSD = \"<br><div class='inliner'>1TB SSD storage</div><div class='inliner-right' style='color: gray;'></div><br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storage').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('128GBSSD').innerHTML = new128GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('256GBSSD').innerHTML = new256GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('512GBSSD').innerHTML = new512GBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('1TBSSD').innerHTML = new1TBSSD;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('storageForm').value=4;\r\n");
      out.write("\t\t\t\t\t\t\t\tstoragePrice = 800;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<button id=\"128GBSSD\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"OneTwoEightGBSSD()\"><br><div class=\"inliner\">128GB SSD storage</div><div class=\"inliner-right\"></div><br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t<br style=\"line-height: 0.5;\">\r\n");
      out.write("\t\t\t\t\t<button id=\"256GBSSD\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"TwoFiveSixGBSSD()\"><br><div class=\"inliner\">256GB SSD storage</div><div class=\"inliner-right\" style=\"color: gray;\">+ $200.00</div>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t<br style=\"line-height: 0.5;\">\r\n");
      out.write("\t\t\t\t\t<button id=\"512GBSSD\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"FiveOneTwoGBSSD()\"><br><div class=\"inliner\">512GB SSD storage</div><div class=\"inliner-right\" style=\"color: gray;\">+ $400.00</div>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t<br style=\"line-height: 0.5;\">\r\n");
      out.write("\t\t\t\t\t<button id=\"1TBSSD\" class=\"btn-default btn-lg btn-block text-left\" onClick=\"OneTBSSD()\"><br><div class=\"inliner\">1TB SSD storage</div><div class=\"inliner-right\" style=\"color: gray;\">+ $800.00</div>&nbsp;</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-btn3\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-mouse\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-close3\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-mouse\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h3>Pre-Installed Software</h3>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t$(\".overlay-btn4\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-fruit\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\".overlay-close4\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-fruit\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<h4><strong>Fruits Cut Pro X</strong></h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-btn4\">Learn more</div>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction noneFruit(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFruit=\"<br>none<br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFruit =\"<div style='line-height: 0.8;'><br></div>Fruits Cut Pro X<div style='color: gray;'>+ $299.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruit').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFruit').innerHTML = newNoneFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFruit').innerHTML = newOnFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruitForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tfruitPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction onFruit(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>Fruits Cut Pro X<br><br></strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFruit=\"<div style='line-height: 0.8;'><br></div>none<div style='color: gray;'>- $299.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFruit =\"<br>Fruits Cut Pro X<br>&nbsp;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruit').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFruit').innerHTML = newNoneFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFruit').innerHTML = newOnFruit;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('fruitForm').value=1;\r\n");
      out.write("\t\t\t\t\t\t\t\tfruitPrice = 299.99;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id =\"NoneFruit\" class=\"btn-default btn-lg btn-block\" onClick=\"noneFruit()\"><br>none<br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id = \"OnFruit\" class=\"btn-default btn-lg btn-block\" onClick=\"onFruit()\"><div style=\"line-height: 0.8;\"><br></div>Fruits Cut Pro X<div style=\"color: gray;\">+ $299.99</div><div style=\"line-height: 0.3;\"><br>&nbsp;</div></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-btn5\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-flower\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeIn();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\".overlay-close5\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-flower\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t\t$(\".overlay-shadow\").fadeOut();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<br><h4><strong>Flower Petal X</strong></h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-btn5\">Show more</div>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tfunction noneFlower(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFlower=\"<br>none<br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFlower =\"<div style='line-height: 0.8;'><br></div>Flower Petal X<div style='color: gray;'>+ $199.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flower').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFlower').innerHTML = newNoneFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFlower').innerHTML = newOnFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flowerForm').value=0;\r\n");
      out.write("\t\t\t\t\t\t\t\tflowerPrice = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction onFlower(){\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newValue = \"<strong>Flower Petal X<br><br></strong>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newNoneFlower=\"<div style='line-height: 0.8;'><br></div>none<div style='color: gray;'>- $199.99</div><div style='line-height: 0.3;'><br>&nbsp;</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tvar newOnFlower =\"<br>Flower Petal X<br>&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flower').innerHTML = newValue;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('NoneFlower').innerHTML = newNoneFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('OnFlower').innerHTML = newOnFlower;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('flowerForm').value=1;\r\n");
      out.write("\t\t\t\t\t\t\t\tflowerPrice = 199.99;\r\n");
      out.write("\t\t\t\t\t\t\t\tvar i= price + memoryPrice + storagePrice + mousePrice  + fruitPrice  + flowerPrice;\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById('priceTelling').innerHTML = i.toFixed(2);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id =\"NoneFlower\" class=\"btn-default btn-lg btn-block\" onClick=\"noneFlower()\"><br>none<br>&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id = \"OnFlower\" class=\"btn-default btn-lg btn-block\" onClick=\"onFlower()\"><div style=\"line-height: 0.8;\"><br></div>Flower Petal X<div style=\"color: gray;\">+ $199.99</div><div style=\"line-height: 0.3;\"><br>&nbsp;</div></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("<p>");
      if (_jspx_meth_sj_005fdatepicker_005f0(_jspx_page_context))
        return;
      out.write("</p><!-- jQueryが動いているかどうかチェック用。本来要らない -->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footerPerchase.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sj_005fdatepicker_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sj:datepicker
    com.jgeppert.struts2.jquery.views.jsp.ui.DatePickerTag _jspx_th_sj_005fdatepicker_005f0 = (com.jgeppert.struts2.jquery.views.jsp.ui.DatePickerTag) _005fjspx_005ftagPool_005fsj_005fdatepicker_0026_005fname_005fid_005fdisplayFormat_005fnobody.get(com.jgeppert.struts2.jquery.views.jsp.ui.DatePickerTag.class);
    _jspx_th_sj_005fdatepicker_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sj_005fdatepicker_005f0.setParent(null);
    // /laptop.jsp(553,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdatepicker_005f0.setName("date");
    // /laptop.jsp(553,3) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdatepicker_005f0.setId("date");
    // /laptop.jsp(553,3) name = displayFormat type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sj_005fdatepicker_005f0.setDisplayFormat("yy/mm/dd");
    int _jspx_eval_sj_005fdatepicker_005f0 = _jspx_th_sj_005fdatepicker_005f0.doStartTag();
    if (_jspx_th_sj_005fdatepicker_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsj_005fdatepicker_0026_005fname_005fid_005fdisplayFormat_005fnobody.reuse(_jspx_th_sj_005fdatepicker_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsj_005fdatepicker_0026_005fname_005fid_005fdisplayFormat_005fnobody.reuse(_jspx_th_sj_005fdatepicker_005f0);
    return false;
  }
}
