/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-12-18 08:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class perchaseProgress_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-mitome/backup-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar!/META-INF/struts-jquery-tags.tld", Long.valueOf(1389609360000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.32.jar", Long.valueOf(1513236930000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar", Long.valueOf(1513236930000L));
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-mitome/backup-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-core-2.3.32.jar!/META-INF/struts-tags.tld", Long.valueOf(1488769580000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fescape_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fescape_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fescape_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write('	');

	int h = (int) session.getAttribute("pcType");
	session.setAttribute("pcType", h);
	int j = (int) session.getAttribute("memoryForm");
	session.setAttribute("memoryForm", j);
	int k = (int) session.getAttribute("storageForm");
	session.setAttribute("storageForm", k);
	int l = (int) session.getAttribute("mouseForm");
	session.setAttribute("mouseForm", l);
	int m = (int) session.getAttribute("fruitForm");
	session.setAttribute("fruitForm", m);
	int o = (int) session.getAttribute("flowerForm");
	session.setAttribute("flowerForm", o);
	float i = (float) session.getAttribute("totalPrice1");
	session.setAttribute("totalPrice1", i);
	
      out.write("\n");
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t<h1 class=\"text-center\">Shop accessories for your Computer.</h1>\n");
      out.write("\t<br>\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"Cure.jpg\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4>ORgangeCare+ for PC<div style=\"line-height: 0.5;\"><br></div>$169.00</h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tGet up to <strong>3 centuries</strong> of accidental damage coverage and 24/7 expert telephone technical support from Apple, the people who know your Mac best.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\tvar airportSelect = 1;\n");
      out.write("\t\t\t\tvar officeSelect = 1;\n");
      out.write("\t\t\t\tvar capsuleSelect = 1;\n");
      out.write("\t\t\t\tfunction CareSubmit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('careCheck').value=1;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction Connector1Submit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('connector1Check').value=1;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction Connector2Submit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('connector2Check').value=1;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction DriveSubmit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('driveCheck').value=1;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction StorageSubmit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('storageCheck').value=1;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction AirportSelectOne(){\n");
      out.write("\t\t\t\t\tairportSelect=1;\n");
      out.write("\t\t\t\t\tdocument.getElementById('airportButton').disabled=false;\n");
      out.write("\t\t\t\t\tdocument.getElementById('airportButton').className=\"btn-block btn-lg btn-primary\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction AirportSelectTwo(){\n");
      out.write("\t\t\t\t\tairportSelect=2;\n");
      out.write("\t\t\t\t\tdocument.getElementById('airportButton').disabled=false;\n");
      out.write("\t\t\t\t\tdocument.getElementById('airportButton').className=\"btn-block btn-lg btn-primary\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction AirportSubmit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('airportCheck').value=airportSelect;\n");
      out.write("\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction CapsuleSubmit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('timeCapsuleCheck').value=capsuleSelect;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction OfficeSelectOne(){\n");
      out.write("\t\t\t\t\tofficeSelect=1;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"officeButton\").disabled = false;\n");
      out.write("\t\t\t\t\tdocument.getElementById('officeButton').className=\"btn-block btn-lg btn-primary\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction OfficeSelectTwo(){\n");
      out.write("\t\t\t\t\tofficeSelect=2;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"officeButton\").disabled = false;\n");
      out.write("\t\t\t\t\tdocument.getElementById('officeButton').className=\"btn-block btn-lg btn-primary\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction OfficeSelectThree(){\n");
      out.write("\t\t\t\t\tofficeSelect=3;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"officeButton\").disabled = false;\n");
      out.write("\t\t\t\t\tdocument.getElementById('officeButton').className=\"btn-block btn-lg btn-primary\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction OfficeSelectFour(){\n");
      out.write("\t\t\t\t\tofficeSelect=4;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"officeButton\").disabled = false;\n");
      out.write("\t\t\t\t\tdocument.getElementById('officeButton').className=\"btn-block btn-lg btn-primary\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tfunction OfficeSubmit(){\n");
      out.write("\t\t\t\t\tdocument.getElementById('officeCheck').value=officeSelect;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t<button  value=\"perchase\" class=\"btn-block btn-lg btn-primary\" onClick=\"CareSubmit()\">Add to Bag</button>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"connector.jpg\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4 style=\"line-height: 1.5;\">Thunderbolt 3 (USB‑C) to Thunderbolt 2 Adapter<br>$49.00</h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tThe Thunderbolt 3 (USB-C) to Thunderbolt 2 Adapter lets you connect Thunderbolt and Thunderbolt 2 devices — a Thunderbolt display, for example — to any Thunderbolt 3 (USB-C) port on your PC.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tNote: This adapter does not support DisplayPort displays like the Apple LED Cinema Display or third-party DisplayPort and Mini DisplayPort displays. Visit the Thunderbolt 3 (USB-C) to Thunderbolt 2 Adapter Apple Support page for more information.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<button  value=\"perchase\" class=\"btn-block btn-lg btn-primary\" onClick=\"Connector1Submit()\">Add to Bag</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"connector2.jpg\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4 style=\"line-height: 1.5;\">USB-C Digital AV Multiport Adapter<br>$69.00</h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tThe USB-C Digital AV Multiport Adapter lets you connect your Mac with Thunderbolt 3 (USB-C) ports to an HDMI-enabled TV or display in up to 1080p at 60Hz or UHD (3840 by 2160) at 30Hz, while also connecting a standard USB device and a USB-C charging cable (up to 60W power pass-through).\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<button  value=\"perchase\" class=\"btn-block btn-lg btn-primary\" onClick=\"Connector2Submit()\">Add to Bag</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div><!-- rowの閉じ -->\n");
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t<p class=\"box\"/>\n");
      out.write("\t<br>\n");
      out.write("\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"diskDrive.jpg\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4>Apple USB SuperDrive<div style=\"line-height: 0.5;\"><br></div>$79.00</h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tCompact and convenient, the external Apple USB SuperDrive connects to your iMac with a single USB cable. It lets you install new software and play and burn both CDs and DVDs, including double-layer DVDs.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<button  value=\"perchase\" class=\"btn-block btn-lg btn-primary\" onClick=\"DriveSubmit()\">Add to Bag</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"mikan10.png\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4 style=\"line-height: 1.5;\">PROMISE Pegasus3 R4 12TB (4 by 3TB) RAID Storage<br>$1,499.00</h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tThe latest generation of Pegasus RAID storage, PROMISE Pegasus3 delivers the power of Thunderbolt 3 technology to Mac users. Now you can get the blazing speeds essential for your high-resolution video and rich media projects, along with the safety and security of full-featured RAID protection. Dual Thunderbolt 3 ports give you 40 Gbps connectivity and the ability to connect up to six daisy-chained devices on a single Thunderbolt 3 port.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<button  value=\"perchase\" class=\"btn-block btn-lg btn-primary\" onClick=\"StorageSubmit()\">Add to Bag</button>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"kuukou.png\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4 style=\"line-height: 1.5;\">AirPort</h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tWith AirPort Express or AirPort Extreme, it’s easier than ever to set up a secure wireless network. AirPort Express is recommended for an apartment, smaller home, or dorm. AirPort Extreme is recommended for a larger home, office, or classroom. Both models deliver outstanding wireless performance, so you get the fastest connection for your Wi-Fi devices. They even offer a convenient guest networking feature and can also be used to extend the range of an existing wireless network.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<div class=\"airportRadio\">\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"airportSelect\" value=\"1\" onClick=\"AirportSelectOne()\">&nbsp;&nbsp;&nbsp;AirPort Express<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$99.00\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<div class=\"airportRadio\">\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"airportSelect\" value=\"2\" onClick=\"AirportSelectTwo()\">&nbsp;&nbsp;&nbsp;AirPort Extreme<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$199.00\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<button  value=\"perchase\" id=\"airportButton\" class=\"btn btn-block btn-lg btn-primary\" onClick=\"AirportSubmit()\" disabled=\"disabled\" >Add to Bag</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div><!-- rowの閉じ -->\n");
      out.write("\n");
      out.write("\t<br>\n");
      out.write("\t<p class=\"box\"/>\n");
      out.write("\t<br>\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"timeCapsule.jpg\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4>AirPort Time Capsule<div style=\"line-height: 0.5;\"><br></div></h4><h4 id=\"capsulePrice\">$299.00</h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tAirPort Time Capsule is a wireless backup device that works automatically with Time Machine to create an easy-to-use, hassle-free backup solution. A 2TB or 3TB hard drive gives you the capacity and safety needed for reliably backing up your Mac computers. AirPort Time Capsule is also a full-featured Wi-Fi base station with 802.11ac technology. So you can set up a high-speed wireless network and back up the Mac computers on your network. All with one device.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\tfunction addElement(select){\n");
      out.write("\t\t\t\t\tif(select.value == \"twoTB\"){\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('capsulePrice').innerHTML = \"$299.00\";\n");
      out.write("\t\t\t\t\t\tcapsuleSelect=1;\n");
      out.write("\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif(select.value == \"threeTB\"){\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('capsulePrice').innerHTML = \"$399.00\";\n");
      out.write("\t\t\t\t\t\tcapsuleSelect=2;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t\t<h4>Storage</h4>\n");
      out.write("\t\t\t<select class=\"form-control\" onchange=\"addElement(this);\">\n");
      out.write("\t\t\t\t<option value=\"twoTB\">2TB</option>\n");
      out.write("\t\t\t\t<option value=\"threeTB\">3TB</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<div style=\"line-height: 0.5;\"><br></div>\n");
      out.write("\t\t\t<button  value=\"perchase\" class=\"btn-block btn-lg btn-primary\" onClick=\"CapsuleSubmit()\">Add to Bag</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t\t<div class=\"text-center\"><img src=\"office.jpg\" height=\"200px\"></div>\n");
      out.write("\t\t\t<h4>Microsoft Office<div style=\"line-height: 0.5;\"><br></div></h4>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5 style=\"line-height: 1.5;\">\n");
      out.write("\t\t\t\tOffice gives you a suite of powerful productivity apps, including Word, Excel, PowerPoint, and OneNote. Choose the version that’s right for you. Office 365 is a convenient annual subscription delivering exclusive monthly upgrades and new features on your Mac, iPad, and iPhone — so you can get things done from virtually anywhere. Office Home & Student 2016 is a one-time purchase that’s ideal for use on a single Mac.\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<div class=\"officeRadio\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\"><input type=\"radio\" name=\"officeSelect\" value=\"1\"  onClick=\"OfficeSelectOne()\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">Microsoft Office 365 Home (1-year Subscription; 5 Licenses)<br>$99.95</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\"><input type=\"radio\" name=\"officeSelect\" value=\"2\" onClick=\"OfficeSelectTwo()\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">Microsoft Office 365 Personal (1-year Subscription; 1 License)<br>$69.95</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\"><input type=\"radio\" name=\"officeSelect\" value=\"3\" onClick=\"OfficeSelectThree()\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">Microsoft Office Home & Student 2016 for Mac<br>$149.95</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-2\"><input type=\"radio\" name=\"officeSelect\" value=\"4\" onClick=\"OfficeSelectFour()\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-10\">Microsoft Office Home & Business 2016 for Mac<br>$229.95</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<button  value=\"perchase\"  id=\"officeButton\" class=\"btn btn-block btn-lg btn-primary\" onClick=\"OfficeSubmit()\" disabled=\"disabled\">Add to Bag</button>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-sm-4\">\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write('	');
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footerPerchaseProgress.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fescape_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /perchaseProgress.jsp(258,1) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("mouseForm");
    // /perchaseProgress.jsp(258,1) name = escape type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setEscape(false);
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fescape_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fescape_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
