/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-12-20 01:49:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recycleFee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-mitome/backup-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar!/META-INF/struts-jquery-tags.tld", Long.valueOf(1389609360000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.32.jar", Long.valueOf(1513236930000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-jquery-plugin-3.7.0.jar", Long.valueOf(1513236930000L));
    _jspx_dependants.put("jar:file:/C:/Users/internousdev/Desktop/workspace/workspace-mitome/backup-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/shop/WEB-INF/lib/struts2-core-2.3.32.jar!/META-INF/struts-tags.tld", Long.valueOf(1488769580000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"background-gray\"></div>\n");
      out.write("\t<br>\n");
      out.write("\t<div class=\"panel panel-default\">\n");
      out.write("\t\t<div class=\"panel-body\" style=\"box-shadow: 1px 1px 5px #c0c0c0;\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-xs-8\">\n");
      out.write("\t\t\t\t\t<h3>California Recycling Fees</h3>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.5;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>New Law Covering Electronics Recycling</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">The State of California launched the nation’s first electronic waste recycling program on Jan. 1, 2005, and Apple wants its customers to understand how this landmark legislation affects their purchases.</h6>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">Beginning Jan. 1, 2005, the Electronic Waste Recycling Act of 2003 (SB 20 and SB 50) requires that customers pay a small fee on some electronics purchases to cover the cost of recycling and disposal.</h6>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">Please read this FAQ to learn how this fee affects your purchases from ORange:</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>Who pays the fee?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">The fee is charged to all end-user consumers, including individuals, enterprise, education, and federal, state and local governments. Sales to resellers are exempt from the fee.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>How will the fee be applied?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">When you purchase a covered product, it will automatically be added to the cost of your order.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>How much is the fee? What products are covered?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">Currently the law requires all products with video displays greater than 4 inches wide to be charged a fee. This includes both CRT monitors and LCD screens.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.5;\"><br></div>\n");
      out.write("\t\t\t\t\t<table class=\"recyle\">\n");
      out.write("\t\t\t\t\t\t<tr class=\"recyle\">\n");
      out.write("\t\t\t\t\t\t\t<th class=\"recyle\">Monitor size</th><th style=\"right: 0;\" class=\"recyle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fee</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr class=\"recyle\">\n");
      out.write("\t\t\t\t\t\t\t<td class=\"recyle\">Greater than 4 inches, less than 15 inches</td><td style=\"right: 0;\" class=\"recyle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$5.00</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr class=\"recyle\">\n");
      out.write("\t\t\t\t\t\t\t<td class=\"recyle\">Greater than 15 inches, less than 35 inches&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style=\"right: 0;\" class=\"recyle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$6.00</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr class=\"recyle\">\n");
      out.write("\t\t\t\t\t\t\t<td class=\"recyle\">Greater than 35 inches</td><td style=\"right: 0;\" class=\"recyle\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$7.00</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.5;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>What about iPod?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">The iPod screen is smaller than 4 inches, so the law does not cover iPod.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>How were the costs determined?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">According to the legislation, the fees cover the actual costs of recycling and disposing of the equipment.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>Where does the money go?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">The fees are sent directly to the State of California, which will redistribute the funds to organizations that transport for recycling and/or recycle equipment.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>Is the California recycle fee taxable?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">No.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>If I return the product, will I receive a credit for the recycle fee previously paid?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">Yes. When a product is returned and a restocking fee is charged, you will receive a credit for the entire recycle fee. If the product is replaced with another covered product, the recycling fee will be charged again.</h6>\n");
      out.write("\t\t\t\t\t<div style=\"line-height: 0.2;\"><br></div>\n");
      out.write("\t\t\t\t\t<h4><strong>Where can I find out more about the law?</strong></h4>\n");
      out.write("\t\t\t\t\t<h6 style=\"line-height: 1.5;\">Visit the State of California’s Electronic Product Management <a href=\"http://www.calrecycle.ca.gov/\">web site.</a></h6>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-xs-4\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<br>&nbsp;\n");
      out.write("\t\t\t<br>&nbsp;\n");
      out.write("\t\t\t<br>&nbsp;\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
